# Phase 1 (Data Collection/preparation part)

In [2]:
import selenium
from selenium import webdriver
import pandas as pd
import numpy as np
from selenium.webdriver.common.by import By
import warnings
warnings.filterwarnings('ignore')
import time

# 1 & 2 The population and literacy rate of each state

In [3]:
driver=webdriver.Chrome()
driver.get('https://www.indiacensus.net/literacy-rate.php')

In [4]:
states = []
population = []
growth = []
for i in driver.find_elements(By.XPATH,'//table[@class="pincode-tbl"]/tbody/tr/td[2]'):
    states.append(i.text)

for i in driver.find_elements(By.XPATH,'//table[@class="pincode-tbl"]/tbody/tr/td[3]'):
    population.append(i.text)
    
for i in driver.find_elements(By.XPATH,'//table[@class="pincode-tbl"]/tbody/tr/td[5]'):
    growth.append(i.text)

populations = pd.DataFrame()
populations['states']= states
populations['poopulation'] = population
populations['literacy'] = growth
populations

                       states  poopulation literacy
0   Andaman & Nicobar Islands      380,581   86.63%
1              Andhra Pradesh   84,580,777   67.02%
2           Arunachal Pradesh    1,383,727   65.38%
3                       Assam   31,205,576   72.19%
4                       Bihar  104,099,452   61.80%
5                  Chandigarh    1,055,450   86.05%
6                Chhattisgarh   25,545,198   70.28%
7      Dadra and Nagar Haveli      343,709   76.24%
8               Daman and Diu      243,247   87.10%
9                       Delhi   16,787,941   86.21%
10                        Goa    1,458,545   88.70%
11                    Gujarat   60,439,692   78.03%
12                    Haryana   25,351,462   75.55%
13           Himachal Pradesh    6,864,602   82.80%
14          Jammu and Kashmir   12,541,302   67.16%
15                  Jharkhand   32,988,134   66.41%
16                  Karnataka   61,095,297   75.36%
17                     Kerala   33,406,061   94.00%
18                Lakshadweep       64,473   91.85%
19             Madhya Pradesh   72,626,809   69.32%
20                Maharashtra  112,374,333   82.34%
21                    Manipur    2,855,794   76.94%
22                  Meghalaya    2,966,889   74.43%
23                    Mizoram    1,097,206   91.33%
24                   Nagaland    1,978,502   79.55%
25                     Orissa   41,974,218   72.87%
26                 Puducherry    1,247,953   85.85%
27                     Punjab   27,743,338   75.84%
28                  Rajasthan   68,548,437   66.11%
29                     Sikkim      610,577   81.42%
30                 Tamil Nadu   72,147,030   80.09%
31                  Telangana   35,193,978   66.54%
32                    Tripura    3,673,917   87.22%
33              Uttar Pradesh  199,812,341   67.68%
34                Uttarakhand   10,086,292   78.82%
35                West Bengal   91,276,115   76.26%

In [5]:
populations.to_csv('E:\\Datatrained\\Castpone project\\population and litercay of states.csv' , index=False)

# Aread of each state

In [6]:
driver = webdriver.Chrome()
driver.get('https://statisticstimes.com/geography/india/indian-states-area.php')

In [9]:
states = []
area = []
for i in driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[2]'):
    states.append(i.text)

for i in driver.find_elements(By.XPATH,'//table[@id="table_id"]/tbody/tr/td[3]'):
    area.append(i.text)
    


areas = pd.DataFrame()
areas['state'] = states
areas['Area km^2'] = area
areas

                                   state Area km^2
0                        A. & N. Islands     8,249
1                         Andhra Pradesh   162,970
2                      Arunachal Pradesh    83,743
3                                  Assam    78,438
4                                  Bihar    94,163
5                             Chandigarh       114
6                           Chhattisgarh   135,192
7   Dadra & Nagar Haveli and Daman & Diu       603
8                                  Delhi     1,483
9                                    Goa     3,702
10                               Gujarat   196,244
11                               Haryana    44,212
12                      Himachal Pradesh    55,673
13                       Jammu & Kashmir    55,538
14                             Jharkhand    79,716
15                             Karnataka   191,791
16                                Kerala    38,852
17                                Ladakh   166,698
18                           Lakshadweep        32
19                        Madhya Pradesh   308,252
20                           Maharashtra   307,713
21                               Manipur    22,327
22                             Meghalaya    22,429
23                               Mizoram    21,081
24                              Nagaland    16,579
25                                Odisha   155,707
26                            Puducherry       490
27                                Punjab    50,362
28                             Rajasthan   342,239
29                                Sikkim     7,096
30                            Tamil Nadu   130,060
31                             Telangana   112,077
32                               Tripura    10,486
33                         Uttar Pradesh   240,928
34                           Uttarakhand    53,483
35                           West Bengal    88,752

In [10]:
areas.to_csv('E:\\Datatrained\\Castpone project\\areas of indian states.csv' , index=False)